version: '3.4'

services:
  webapp:
    image: webapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: database
      DB_USER: user
      DB_PASSWORD: password
      DB_DB: database
      REDIS_HOST: redis  
      REDIS_PORT: 6379   # puerto por defecto de Redis
    ports:
      - 8000:8000
    networks:
      - default
    volumes:
      - .:/opt/app
    command: poetry run uvicorn app:app --reload --host 0.0.0.0 --port 8000

    depends_on:
      - db
      - redis  

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/:/docker-entrypoint-initdb.d/
    networks:
      - default

  redis:
    image: redis:alpine  
    ports:
      - 6379:6379
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: test 
    ports:
      - 5050:80
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
