name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v3
    - name: Checkout  
      uses: hoverkraft-tech/compose-action@v2.0.0

    - name: Run tests with coverage
      run: |
        docker compose exec webapp poetry run coverage run -m unittest test-api  # ejecutar tests específicos
        docker compose exec webapp poetry run coverage report --fail-under=85  # verificar que el coverage sea al menos 85%
      
    - name: Leer versión
      id: version
      run: |
        VERSION=$(cat version.txt)
        echo "::set-output name=version::$VERSION"

    - name: Build the Docker image
      if: success()  # solo construir la imagen si los tests y el coverage pasaron
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ghcr.io --username EngSteven --password-stdin
        docker build . --file Dockerfile --tag ghcr.io/engsteven/py01-bd2:${{ steps.version.outputs.version }}
        docker push ghcr.io/engsteven/py01-bd2:${{ steps.version.outputs.version }}

    - name: Incrementar versión
      if: success()  # solo incrementar la versión si los tests y el coverage pasaron
      run: |
        chmod +x increment_version.sh
        bash increment_version.sh
