name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    - name: Run tests and check coverage
      run: |
        poetry run coverage run api-test.py
        poetry run coverage report --fail-under=85

  build:
    runs-on: ubuntu-latest
    needs: test  # Solo se ejecuta si el job 'test' es exitoso

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t engsteven/py01-bd2:latest .

    - name: Push Docker image
      run: |
        docker tag engsteven/py01-bd2:latest engsteven/py01-bd2:latest
        docker push engsteven/py01-bd2:latest
